modLoader = "javafml"
loaderVersion = "*"
#issueTrackerURL = ""
license = "All Rights Reserved"
clientSideOnly = true

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
authors = "HollowHorizon"
description = '''
${description}
'''
#logoFile = ""

[[dependencies.${id}]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${id}]]
modId = "ftbquests"
mandatory = true
versionRange = "[2001.4.14,)"
ordering = "AFTER"
side = "BOTH"
